name: Daily Scrapper Routine with Python
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run-routine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name: browser install
        run: playwright install

      - name: Execute scrapper
        run: python main_execution.py

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: r√©sultats-routine
          path: |
            *.csv
            *.log
